version: '3'

services:
  phoenix:
    build:
      context: .
    volumes:
       - ./:/app
       - ./samples/movies:/movies
    command: >
        bash -c "mix deps.get && mix ecto.create && mix test"

  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database