version: '3'

volumes:
  postgres-data:

services:
  phoenix:
    build: .
    volumes:
      - ./:/app
      - /Users/chazgoodare/mount/external/movies:/movies
      - /Users/chazgoodare/mount/external/shows:/tv
    ports:
      - "4000:4000"

  postgresql:
    image: 'bitnami/postgresql:14'
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
    
  postgresql-test:
    image: 'bitnami/postgresql:14'
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database

  test:
    build: .
    volumes:
       - ./:/app
       - ./samples/movies:/movies
       - ./samples/shows:/shows
    command: >
        bash -c "mix deps.get && mix ecto.create && mix test"