version: '3'

volumes:
  db-data:

services:
  phoenix:
    build: .
    volumes:
      - ./:/app
      - /Users/chazgoodare/mount/external/movies:/movies
      - /Users/chazgoodare/mount/external/tv:/tv
    ports:
      - "4000:4000"

  rtsp-simple-server:
    image: 'aler9/rtsp-simple-server'
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml

  guessit:
    image: 'guessit/guessit-rest'
    ports:
      - "8080:80"

  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - db-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
    
  postgresql-test:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database

  test:
    build: .
    volumes:
       - ./:/app
       - ./samples/movies:/movies
    command: >
        bash -c "mix deps.get && mix ecto.create && mix test"