version: "3"

services:
  web:
    build: .
    volumes:
      - ./:/app
      - ./fixtures/movies:/movies
      - ./fixtures/shows:/shows
    ports:
      - 4000:4000
    environment:
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword
    command: >
        bash -c "mix phx.server"
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:14
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database

  test-web:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
      test-postgresql:
        condition: service_healthy
      test-radarr:
        condition: service_healthy
      test-sonarr:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./fixtures/movies:/movies
      - ./fixtures/shows:/shows
    environment:
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql
    command: >
        bash -c "mix deps.get && mix ecto.create && mix test"

  test-postgresql:
    image: bitnami/postgresql:14
    healthcheck:
      test: "exit 0"
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database

  test-radarr:
    image: mdhiggins/radarr-sma
    healthcheck:
      test: curl --fail http://localhost:7878 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./fixtures/radarr:/config
      - ./fixtures/movies:/movies
    ports:
      - 7878:7878

  test-sonarr:
    image: mdhiggins/sonarr-sma
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./fixtures/sonarr:/config
      - ./fixtures/shows:/shows
    ports:
      - 8989:8989