version: "3.4"

services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - ./fixtures/movies:/movies
      - ./fixtures/shows:/shows
    environment:
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword
    command: >
        bash -c "mix phx.server"
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:14
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    healthcheck:
      test: "exit 0"

  test-web:
    build: .
    volumes:
      - ./:/app
      - ./fixtures/movies:/movies
      - ./fixtures/shows:/shows
    environment:
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database
      - DB_HOSTNAME=postgresql
    command: >
        bash -c "mix deps.get && mix ecto.create && mix test"
    depends_on:
      postgresql:
        condition: service_healthy
      test-postgresql:
        condition: service_healthy
      test-radarr:
        condition: service_healthy
      test-sonarr:
        condition: service_healthy

  test-postgresql:
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    healthcheck:
      test: "exit 0"

  test-radarr:
    image: lscr.io/linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - ./fixtures/radarr:/config
      - ./fixtures/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl --fail test-radarr:7878 || exit 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  test-sonarr:
    image: lscr.io/linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - ./fixtures/sonarr:/config
      - ./fixtures/shows:/shows
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl --fail test-sonarr:8989 || exit 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s