services:

  midarr:
    container_name: midarr
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - ./priv/library:/library
    environment:
      - APP_URL=http://midarr:4000

      - DB_HOSTNAME=postgresql
      - DB_HOSTNAME_TEST=postgresql-test
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
      - DB_DATABASE=my_database

      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword

      - RADARR_BASE_URL=http://radarr:7878
      - RADARR_API_KEY=d031e8c9b9df4b2fab311d1c3b3fa2c5
      - SONARR_BASE_URL=http://sonarr:8989
      - SONARR_API_KEY=1accda4476394bfcaddefe8c4fd77d4a

#      - RADARR_BASE_URL=http://radarr-demo.home.lan
#      - RADARR_API_KEY=6c2c2aa13b8e483880dfca563f4c84fe
#      - SONARR_BASE_URL=http://sonarr-demo.home.lan
#      - SONARR_API_KEY=bde28b492c9a4e62af4aead8c7ae88c2
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-test:
        condition: service_healthy
      radarr:
        condition: service_healthy
      sonarr:
        condition: service_healthy
    command: bash -c "chmod u+x priv/entry-point-local.sh && ./priv/entry-point-local.sh"

  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"

  postgresql-test:
    container_name: postgresql-test
    image: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=my_database
    healthcheck:
      test: "exit 0"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:version-4.1.0.6175
    ports:
      - 7878:7878
    volumes:
      - ./priv/radarr/config.xml:/config/config.xml
      - ./priv/library:/library
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "exit 0"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:version-3.0.9.1549
    ports:
      - 8989:8989
    volumes:
      - ./priv/sonarr/config.xml:/config/config.xml
      - ./priv/library:/library
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "exit 0"