name: Feature

on:
  push:
    branches: [ 'feature/**' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: midarr-server_midarr:latest

    - name: Up services
      run: docker compose up -d

    - name: Run tests
      run: docker run --network=midarr-server_default midarr-server_midarr:latest mix test