name: Feature

on:
  push:
    branches: [ 'feature/**' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Up services
      run: docker compose up -d

    - name: Run tests
      run: docker run --network=midarr-server_default --env DB_USERNAME=my_user --env DB_PASSWORD=my_password --env DB_DATABASE=my_database --env DB_HOSTNAME=postgresql --env TEST_DB_HOSTNAME=test-postgresql --mount type=bind,src=/fixtures/movies,dst=/movies --mount type=bind,src=/fixtures/shows,dst=/shows midarr-server_midarr:latest mix test